<?php
/**
 * Created by PhpStorm.
 * User: Sorrell
 * Date: 23/04/14
 * Time: 23:17
 */

namespace Resources\Config;

//A class containing hard-coded configuration data
class Cfg{
    public static $locale       = "ro-ro";
    public static $appTitle     = "Materna";
    public static $appTheme     = "Materna";
    public static $appSupport   = "iftode.bogdan@gmail.com";

    public static $cfgDbHost    = "localhost";
    public static $cfgDbUser    = "materna";
    public static $cfgDbPass    = "1123581321";
    public static $cfgDbSchema  = "materna";
}